# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 00:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='register',
            old_name='fullname',
            new_name='password',
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default=datetime.datetime(2016, 3, 9, 0, 31, 19, 44500, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
