# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='fullname',
            new_name='username',
        ),
    ]
