# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160204_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
