# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 22:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160204_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default=datetime.datetime(2016, 2, 7, 22, 26, 47, 523586, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
