# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 21:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20160312_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('listofusers', models.CharField(max_length=500)),
                ('roomname', models.CharField(max_length=25)),
                ('expirydate', models.DateTimeField(blank=True, default=datetime.date(2016, 3, 17))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
