# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 21:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_roominstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominstance',
            name='expirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 17, 16, 11, 22, 570042)),
        ),
    ]
