# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160316_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominstance',
            name='expirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 17, 16, 12, 19, 845630)),
        ),
        migrations.AlterField(
            model_name='roominstance',
            name='listofusers',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='roominstance',
            name='roomname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
