# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160316_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominstance',
            name='expirydate',
        ),
        migrations.AddField(
            model_name='roominstance',
            name='creationdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
