# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 12:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160317_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominstance',
            name='creationdate',
        ),
        migrations.AddField(
            model_name='roominstance',
            name='expirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 18, 12, 47, 58, 433741)),
        ),
        migrations.AddField(
            model_name='roominstance',
            name='isexpired',
            field=models.BooleanField(default=False),
        ),
    ]
