# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 18:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160317_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominstance',
            name='listofpref',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='roominstance',
            name='expirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 20, 18, 10, 46, 643147)),
        ),
    ]
