# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 23:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20160322_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominstance',
            name='expirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 23, 23, 4, 21, 358722)),
        ),
    ]
