# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 15:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20160323_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominstance',
            name='expirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 25, 15, 42, 27, 250238)),
        ),
    ]
