# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 15:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20160324_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominstance',
            name='chathistory',
            field=models.CharField(blank=True, max_length=9999999999999999, null=True),
        ),
        migrations.AlterField(
            model_name='roominstance',
            name='expirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 26, 15, 42, 25, 305459)),
        ),
    ]
