# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 23:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20160325_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominstance',
            name='expirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 26, 23, 26, 5, 894158)),
        ),
        migrations.AlterField(
            model_name='roominstance',
            name='listofusers',
            field=models.CharField(blank=True, max_length=9999999999999999, null=True),
        ),
    ]
