# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 18:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20160325_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominstance',
            name='roomsetting',
            field=models.CharField(blank=True, max_length=999999999, null=True),
        ),
        migrations.AlterField(
            model_name='roominstance',
            name='expirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 28, 18, 53, 42, 378998)),
        ),
    ]
