# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 20:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20160327_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominstance',
            name='lastresult',
            field=models.CharField(blank=True, max_length=999999999, null=True),
        ),
        migrations.AlterField(
            model_name='roominstance',
            name='expirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 28, 20, 13, 41, 463896)),
        ),
    ]
