# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20160327_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominstance',
            name='expirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 3, 28, 20, 50, 12, 486901)),
        ),
        migrations.AlterField(
            model_name='roominstance',
            name='roomsetting',
            field=models.CharField(blank=True, max_length=9999999999999999, null=True),
        ),
    ]
