# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 23:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20160328_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pendingfriends',
            field=models.CharField(blank=True, max_length=999999999, null=True),
        ),
        migrations.AlterField(
            model_name='roominstance',
            name='expirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 4, 3, 23, 24, 45, 654318)),
        ),
    ]
