# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 02:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20160402_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominstance',
            name='expirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 4, 4, 2, 20, 34, 590628)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pendingfriends',
            field=models.CharField(default='[]', max_length=999999999, null=True),
        ),
    ]
