# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 22:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20160403_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pendingnotifications',
            field=models.CharField(default='[]', max_length=999999999, null=True),
        ),
        migrations.AlterField(
            model_name='roominstance',
            name='expirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 4, 5, 22, 32, 40, 107753)),
        ),
    ]
