# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20160404_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominstance',
            name='expirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 4, 12, 11, 27, 22, 630145)),
        ),
        migrations.AlterField(
            model_name='roominstance',
            name='listofpref',
            field=models.CharField(blank=True, default='[]', max_length=9999999999999999, null=True),
        ),
        migrations.AlterField(
            model_name='roominstance',
            name='listofusers',
            field=models.CharField(blank=True, default='[]', max_length=9999999999999999, null=True),
        ),
    ]
