# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-30 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20160411_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominstance',
            name='expirydate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 1, 11, 35, 35, 322102)),
        ),
    ]
