XXXXXXXXX XXXXX
XXXXXX
  XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX
  XXXXXXX
  XXXXXX
    XXXX XXXXXXXXXXXXXXX
    XXXXXXXX

  XXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
  XXX XXXXXX X XXX
  XXX XXXXXXX X XXX
  XXX XXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXX

  XXXXXXXX XXXXXXXXX X
    XXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXX XXXXX XXXXX XXXX XXXXXXX
      XXXXX XXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXX XXXX
    XXXXXXXXXXXXXX X XXXXXXXX
    XXXXXXXXXXXX X XXXXXXXXXXXXX
    XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
    XXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXX
        XXX

    XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
      XXX XXXX X X XX X X XXXXXXXXXXXXXXX XXXX X
        XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX X XXXXXXX
        XX XXXXXXX XXXXXX XXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXX
        XXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX
        XX XXXX XX XXXXXX XXXX XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXX
      X
      XXXXXXXXXXXXXXXXXXXXX
    XXX
  X
  XX
  XXXXXXX XXX XXX XXXXXXXXX XXXXXXX
  XX
  XXXXXXXX XXXXXXXXXXXXXXXXXX XX X
    XXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXX XXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXX
    X
  X
  XX
  XXXXXXX XXXX XXXXXXX XXX XXXX XXXXXX XXX XXXXXX
  XX
  XXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXXXXXXXXX XXXXXXX X
      XX XXXXXX XXXXX XXXXXXX XXXX XXX XX XXXXXXX
      XX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX X XXXXX
      X

      XX XXXXXXXX XXXXXX
      XX XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX        
      X
    X
  X

  XX
  XXXXXX XXXX XXXXXXXX XXXX XXXXXXXX XXX XXXXXX
  XX
  XXXXXXXX XXXXXXXXXXXXXXXXXXX X
    XXX XXXXXXX X XXX
    XXXXXXX XX XXXXXXXXXX
    XXXXXXX XX XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX X XXXXXXXXXX X XXXXXXXXXXX
    XXXXXXX XX XXXXXXXXXX XXXXXXX X XXXXXXXXX X XXXX X XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XX XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXX XX XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX      
    X
    XX XXXXXXXXXXXXXX X
      XXX XXXXXXXXXX X XXX
      XXX XXXX X X XX X X XX XXXX X
        XX XXXXXXXXXXXXX X XX X XXXXX X
          XXXXXXXXXX XX XXXXXXXXXXX
        X XXXX X
          XXXXXXXXXX XX XXXXXXXXXXX
        X
      X
      XXXXXXX XX XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
    X
    XX XXXXXXXXXXXXXXX X
      XXX XXXXXXX X XXXXXXXXXXXXXX
      XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXX XX XXXXX X 
        XXXXXXX X XXXXXXXXX X XXXXXXXXXXXXX X XXXX
        XXXXXXX X XXXXXXXX
      X
      XXXXXXX XX XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X XXXXXXX X XXXX X XXXXXXX X XXXXXXXXXXXXXXXXX
    X
    XXXXXXX XX XXXXXXXXXXX
    XXXXXX XXXXXXXX
  X
    XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXX
    XXXXXXXXX
  XXXXXXX
XXXXXXX